name: Lint & Build

on: push

jobs:
  macos:
    name: Lint & Build
    runs-on: macos-latest
    steps:
      - uses: fwal/setup-swift@v1
      - uses: actions/checkout@v3
      - name: Lint
        run: swiftlint lint --reporter github-actions-logging --strict
      - name: Build
        run: swift build
#      - name: Test
#        run: swift test
